# https://github.com/turnabout/turnabout.github.io
name: GitHub pages

# Build on push to develop
on:
    push:
        branches:
            - main

jobs:
    # Deploy to GitHub pages
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3.5.2
                with:
                    ref: main
                    submodules: true  # Add submodules to fetch Zola theme
                    fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
            -   name: Build and deploy
                uses: shalzz/zola-deploy-action@v0.17.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
